[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control | Shift"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "FantasqueSansM NerdFont"
style = "Bold"

[font.italic]
family = "FantasqueSansM NerdFont"
style = "Italic"

[font.normal]
family = "FantasqueSansM NerdFont"
style = "Regular"

[[hints.enabled]]
action = "Copy"
regex = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
regex = 'arn:aws:[a-zA-Z0-9-]+:[a-zA-Z0-9-]*:[0-9]*:[a-zA-Z0-9-_:\\/]+'

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
regex = '(https?://[^\s]+)'

[hints.enabled.binding]
key = "O"
mods = "Control | Shift"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
regex = "sha256:([0-9a-f]{64})"

[hints.enabled.binding]
key = "S"
mods = "Control | Shift"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
post_processing = true
regex = '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

[hints.enabled.mouse]
enabled = true

[window]
dynamic_title = true
opacity = 0.96

[window.padding]
x = 3
y = 3

[keyboard]
