#!/bin/bash

export EDITOR="nvim"

alias zshrc='${=EDITOR} ${ZDOTDIR:-$HOME}/.zshrc'

#
# Docker
# 
alias d="docker"
alias dc="docker compose"

#
# Vim
#
alias vi="vim"
alias vim="nvim"

#
# Easy navigation
# 
alias ..="cd .."
alias ...="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias ~="cd ~"

#
# Shortcuts
#
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias p="cd ~/projects"

#
# Git
#
alias g="git"

#
# List files
#
alias ls="exa"
alias ll="exa -alh"
alias tree="exa --tree"

# list all files colorized in long format
alias l="ls -lF ${colorflag}"
# list all files colorized in long format, excluding . and ..
alias la="ls -lAF ${colorflag}"
# list only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

#
# Grep
#
# Always enable colored `grep` output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#
# Networks
#
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

#
# Translation
# 
alias trs_k2e="trans -b :en"
alias trs_e2k="trans -b :ko"

#
# ETC
#

# reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

# print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias lg='lazygit'
