vim.opt.backup = false                        -- creates a backup files
vim.opt.clipboard = "unnamedplus"             -- allow neovim to access to system clipboard
vim.opt.fileencoding = "utf-8"                -- the encoding wirtten to a file
vim.opt.hlsearch = true                       -- highlight all matches on previous search pattern
vim.opt.ignorecase = true                     -- ignore case in search patterns
vim.opt.pumheight = 10                        -- pop up menu height
vim.opt.showmode = false                      -- we don't need to see things like -- INSERT -- anymore
vim.opt.showtabline = 2                       -- always show tabs
vim.opt.smartcase = true                      -- smart case
vim.opt.smartindent = true                    -- make indenting smarter again
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.timeoutlen = 300
vim.opt.undofile = true
vim.opt.updatetime = 300
vim.opt.writebackup = false
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.cursorline = true
vim.opt.numberwidth = 4
vim.opt.signcolumn = "yes"
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
